language: cpp

os:
  - linux
  #- osx

compiler:
  - clang
  - gcc

script:
  - cd docs/src
  - ./configure
  - make
  - cd ../..
  - ./configure --prefix=$PWD/tempbuild --with-zlib --enable-bigfile
  - make
  - make install

branches:
  only:
  - master

notifications:
    slack: htdig:KJALZaL1b3jsXdVMir6cyTYI
    irc:
      channels:
        - "chat.freenode.net##hldig"
      skip_join: true
      use_notice: true
      on_success: change
      template:
        - "[%{repository_name}#%{branch}@%{commit}] %{author}: %{message} %{build_url}"
