language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os:linux
      compiler: clang
    - os: osx
      osx_image: xcode9.3beta
      compiler: gcc
    - os: osx
      osx_image: xcode9.3beta
      compiler: clang

script:
  - cd docs/src
  - ./configure
  - make
  - cd ../..
  - ./configure --prefix=$PWD/tempbuild --with-zlib --enable-bigfile
  - make
  - make install

branches:
  only:
  - master

notifications:
    irc:
      channels:
        - "chat.freenode.net##hldig"
      skip_join: true
      use_notice: true
      on_success: change
      template:
        - "[%{repository_name}#%{branch}@%{commit}] %{author}: %{message} %{build_url}"
