language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      osx_image: xcode9.3beta

script:
  - cd docs/src
  - ./configure
  - make
  - cd ../..
  - ./configure --prefix=$PWD/tempbuild --with-zlib --enable-bigfile
  - make
  - make install

branches:
  only:
  - master

notifications:
    irc:
      channels:
        - "chat.freenode.net#hldig"
      skip_join: false
      use_notice: false
      on_success: change
      on_failure: change
      on_error: always
      template:
        - "[%{repository_name}#%{branch}@%{commit}] Authored by %{author} | Result: %{message} %{build_url}"
